CompFUSE/DCA

- CMakeLists.txt
With this reorder I am able to build on my laptop, as MAGMA requires the linear algebra libraries in the DCA_EXTERNAL_LIBS list.
> Link external libs at the end.

- applications/cluster_solver_check/cluster_solver_check.cpp
- include/dca/parallel/mpi_concurrency/mpi_collective_sum.hpp
- test/integration/statistical_tests/square_lattice/ctaux_square_lattice_validation_stattest.cpp
- test/unit/parallel/mpi_concurrency/mpi_collective_sum_test.cpp
The covariance matrix should be computed against the sample average, not the expected value, as it was done in the statistical validation test. This PR fix this issue in the cluster_solver_check application.
> Fix cluster solver check

- cmake/dca_mpi.cmake
- cmake/dca_testing.cmake
- src/parallel/mpi_concurrency/CMakeLists.txt
This just adds a find_package(MPI) if the compiler has not already got MPI support and then adds include dirs and link libs to the build (which would be added by the MPI compiler if it was used)
> Support finding MPI using find_package(MPI) for local compilation

- include/dca/phys/domains/cluster/momentum_exchange_domain.hpp
- include/dca/phys/domains/time_and_frequency/frequency_exchange_domain.hpp
- include/dca/phys/parameters/four_point_parameters.hpp
- src/phys/domains/cluster/CMakeLists.txt
- src/phys/domains/cluster/momentum_exchange_domain.cpp
- src/phys/domains/time_and_frequency/CMakeLists.txt
- src/phys/domains/time_and_frequency/frequency_exchange_domain.cpp
- test/unit/phys/domains/cluster/CMakeLists.txt
- test/unit/phys/domains/cluster/momentum_exchage_domain_test.cpp
- test/unit/phys/domains/time_and_frequency/CMakeLists.txt
- test/unit/phys/domains/time_and_frequency/frequency_exchage_domain_test.cpp
- test/unit/phys/parameters/four_point_parameters/four_point_parameters_test.cpp
- test/unit/phys/parameters/four_point_parameters/input_read_all.json
- tools/complete_input.json
Defines the domains used for the computation of multiple frequencies and momenta exchange.
-  ~While a unit test is missing,~ the code itself can be reviewed.
- Issue #19 can be taken care of after the `gpu_trunk` merge.
> Created domains for momentum and frequency exchange.

- include/dca/math/nfft/nfft_helper.cu.hpp
> Use two arguments in static_assert.

- include/dca/phys/domains/time_and_frequency/vertex_frequency_domain.hpp
Should have been part of #20.
The domain containing the tp frequencies where G needs to be computed, uses the exchange domain to determine its size.
> Vertex frequency domain

- applications/cluster_solver_check/cluster_solver_check.cpp
- applications/dca/main_dca.cpp
- include/dca/parallel/mpi_concurrency/mpi_concurrency.hpp
- include/dca/parallel/mpi_concurrency/mpi_initializer.hpp
- include/dca/parallel/no_concurrency/no_concurrency.hpp
- src/parallel/mpi_concurrency/mpi_concurrency.cpp
- src/parallel/mpi_concurrency/mpi_initializer.cpp
- src/parallel/no_concurrency/no_concurrency.cpp
I realized that both with the old master and the current version, if a single processor throws an unhandled exception (i.e. by reading an input file or by running out of memory), and the stack unwinds until MPI_Finalize is called, only that process terminates, while the rest hangs on the first MPI communication. 
This PR shuts down all the processes unless a different behaviour is specified (used for selectively killing processors upon driver failure).
If you have a better implementation in mind, please say so.
> Abort the MPI network upon unhandled exception.

- include/dca/parallel/mpi_concurrency/mpi_type_map.hpp
- include/dca/phys/parameters/four_point_parameters.hpp
- include/dca/phys/parameters/mci_parameters.hpp
- test/unit/parallel/mpi_concurrency/mpi_type_map_test.cpp
Improvement of #27.
I found a way to pass a general enumeration to our MPI broadcast wrapper, so we can store them directly as parameter members.
> MPITypeMap for enumerations.

- cmake/dca_compiler_options.cmake
- include/dca/linalg/util/memory.hpp
- include/dca/math/geometry/tetrahedron_mesh/tetrahedron_mesh_initializer.hpp
- include/dca/phys/dca_step/cluster_solver/ctaux/ctaux_cluster_solver.hpp
- include/dca/phys/dca_step/cluster_solver/exact_diagonalization_advanced/greens_functions/tp_greens_function.hpp
- test/integration/phys/lattice_mapping/lattice_mapping_sp_test.cpp
- test/unit/function/CMakeLists.txt
- test/unit/linalg/matrixop_complex_cpu_test.cpp
- test/unit/linalg/matrixop_real_cpu_test.cpp
Fixes parts of #56, i.e.
-Wunused-variable
-Wgnu-zero-variadic-macro-arguments
-Wself-assign-overloaded
-Wself-move
> Fix compiler warnings

- include/dca/phys/dca_step/cluster_solver/stdthread_qmci/stdthread_qmci_accumulator.hpp
- include/dca/phys/dca_step/cluster_solver/stdthread_qmci/stdthread_qmci_cluster_solver.hpp
- include/dca/phys/parameters/mci_parameters.hpp
- test/integration/cluster_solver/stdthread_qmci/stdthread_ctaux_tp_test_shared_input.json
- test/integration/statistical_tests/square_lattice/square_lattice_input.json
- tools/complete_input.json
Changes the work distribution in the PR solver and gives the option (on by default) to solve https://github.com/CompFUSE/DCA-develop/issues/185. 
Previously the measurements per process were split evenly at the beginning among accumulators.
Now it depends on the parameter `fix_meas_per_walker()`:
- if false the total number of measurements per process is reached independently on the contribution of each walker. Should provide better load balance.
- if true each walker contributes a fixed amount of measurements. It is more statistically safe.
> Split number of measurements among walkers.

- test/unit/function/CMakeLists.txt
> Call target_compile_options only if test is built.

- include/dca/phys/models/analytic_hamiltonians/twoband_chain.hpp
- test/integration/exact_diagonalization_advanced/CMakeLists.txt
- test/unit/phys/dca_algorithms/CMakeLists.txt
- test/unit/phys/dca_step/lattice_mapping/deconvolution/CMakeLists.txt
- test/unit/phys/models/CMakeLists.txt
- test/unit/phys/models/analytic_hamiltonians/CMakeLists.txt
- test/unit/phys/models/material_hamiltonians/CMakeLists.txt
- test/unit/phys/parameters/model_parameters/CMakeLists.txt
FFTW include dir was missing in several dca_add_gtest calls.
> FFTW include dir fixes

- include/dca/parallel/mpi_concurrency/mpi_collective_sum.hpp
- include/dca/parallel/no_concurrency/serial_collective_sum.hpp
- include/dca/phys/dca_data/dca_data.hpp
- include/dca/phys/dca_step/cluster_solver/ctaux/ctaux_cluster_solver.hpp
- test/unit/parallel/mpi_concurrency/mpi_collective_sum_test.cpp
Compute the jackknife error on the G(r,t) and G(k,t) provided by the CT-AUX walker (Useful for validating the phase factors changes).
> Jack knife.

- include/dca/phys/dca_data/dca_data.hpp
- include/dca/phys/dca_step/cluster_solver/ctaux/ctaux_cluster_solver.hpp
I did not store correctly the result of the G4 error computation. If we were using c++17, the jackknifeError function should have a [[nodiscard]] attribute.
 
> Fixed error computation of G4.

- include/dca/phys/dca_step/cluster_solver/ctaux/accumulator/tp/tp_equal_time_accumulator.hpp
- include/dca/phys/dca_step/cluster_solver/ctaux/structs/read_write_config.hpp
- test/unit/phys/dca_step/cluster_solver/ctaux/structs/input.json
Solves the problem reported by @maierta by fixing the read of the CT-AUX configuration.
In addition, the initialization of the equal time accumulator is fixed, as it was triggering an assertion while running the input file relative to #127.
> Correct anitoperiodic interpolation for G0, vertex_pair.delta_r no longer  dropped

- include/dca/phys/dca_step/cluster_solver/stdthread_qmci/stdthread_qmci_cluster_solver.hpp
- include/dca/phys/parameters/mci_parameters.hpp
- include/dca/phys/parameters/parameters.hpp
- test/system-level/dca/input.dca_sp_DCA+_mpi_test.json
- test/system-level/dca/input.dca_sp_DCA+_thread_test.json
- test/unit/phys/parameters/mci_parameters/input_read_all.json
- test/unit/phys/parameters/mci_parameters/mci_parameters_test.cpp
- tools/complete_input.json
Reading the configuration from the previous iteration is now optional.
> Configuration storage between iterations is optional. Default: off.

- include/dca/function/function.hpp
- include/dca/phys/dca_analysis/bse_solver/bse_cluster_solver.hpp
- include/dca/phys/dca_analysis/bse_solver/bse_lattice_solver.hpp
- include/dca/phys/dca_analysis/bse_solver/bse_solver.hpp
- include/dca/phys/dca_data/dca_data.hpp
- include/dca/phys/dca_step/cluster_mapping/coarsegraining/coarsegraining_tp.hpp
- include/dca/phys/dca_step/cluster_solver/ctaux/ctaux_accumulator.hpp
- include/dca/phys/dca_step/cluster_solver/ctaux/ctaux_cluster_solver.hpp
- include/dca/phys/dca_step/cluster_solver/exact_diagonalization_advanced/ed_cluster_solver.hpp
- include/dca/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/tp_accumulator.hpp
- include/dca/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/tp_accumulator_gpu.hpp
- include/dca/phys/dca_step/symmetrization/diagrammatic_symmetries.hpp
- include/dca/phys/four_point_type.hpp
- include/dca/phys/parameters/four_point_parameters.hpp
- include/dca/phys/parameters/parameters.hpp
- misc/wiki/Parameters.md
- src/phys/four_point_type.cpp
- test/integration/cluster_solver/stdthread_qmci/stdthread_ctaux_tp_test.cpp
- test/performance/phys/accumulation/tp_accumulation_performance_test.cpp
- test/unit/function/function_library_test.cpp
- test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/tp_accumulator_gpu_test.cpp
- test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/tp_accumulator_particle_hole_test.cpp
- test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/tp_accumulator_singleband_gpu_test.cpp
- test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/tp_accumulator_singleband_test.cpp
- test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/tp_accumulator_test.cpp
- test/unit/phys/parameters/four_point_parameters/four_point_parameters_test.cpp
- test/unit/phys/parameters/four_point_parameters/input_read_all.json
- test/unit/phys/parameters/four_point_parameters/input_read_legacy.json
- tools/complete_input.json
Depends on #138.
- Fixes issue 137 from DCA-develop by removing the duplicated parameter.
- Allow the code to be more maintainable with respect to the addition of new G4 channels.
- The function class now copies the name during construction. This violates the rule that copy/move constructors should behave identically to the assignment operator, but this allows the names a vector of functions to not break upon reallocation, which is particularly important if the code or tests rely on the name. The rationale would be that we do not want to erase a pre-existing name upon copying the values, but we are free to utilize another name while constructing a new function.
The wiki needs to be updated upon approval.
> Properly store multiple G4 channel in the parameters.

- include/dca/phys/dca_data/dca_data.hpp
Partially addresses #145 by going with the first option.
While modifying CT-INT and ED to work with a non-double-counted hamiltonian is easy, changing CT-AUX is more involved and dangerous for multi-band systems.  Also, this way it is easier to deal with intersite interactions on small clusters, where neighbors and next to nearest neighbors could overlap. 
So, for now, I opted to add a comment and a check on this issue, while I believe that @maierta  would prefer to eventually remove the double counting altogether.
> Added comment and check about double counting.

- build-aux/summit_load_modules.sh
They compiled a new magma 2.5 module with gcc-8 on Summit which seems to be working correctly without the long initialization time.
> Update magma and gcc modules.

- include/dca/linalg/util/allocators/pinned_allocator.hpp
- include/dca/testing/type_testing.hpp
- test/unit/linalg/util/CMakeLists.txt
- test/unit/linalg/util/pinned_allocator_test.cpp
So I'm not sure what your intention here is @gbalduzz its possible you may want to change the behavior of the comparison so that only when T == U is the comparison true.
> If we're going to start implementing C++ Allocators we should do them properly.

- include/dca/linalg/util/allocators/pinned_allocator.hpp
- include/dca/testing/type_testing.hpp
- test/unit/linalg/util/CMakeLists.txt
- test/unit/linalg/util/pinned_allocator_test.cpp
I found the implementation very confusing. I think this is simpler, equivalent and it passes the unit test.
> De obfuscate move and shrink

- include/dca/parallel/mpi_concurrency/mpi_type_map.hpp
- test/unit/parallel/mpi_concurrency/mpi_type_map_test.cpp
This fixes some tests that failed on my laptop (mpich 3.3.1)
> Fix MPI datatype using FORTRAN complex types instead of CXX types

- build-aux/summit.cmake
swap -n and -a args in jsrun to ensure tests run smoothly on Summit
> Fix jsrun args for running tests on Summit

- include/dca/phys/parameters/mci_parameters.hpp
- misc/wiki/Parameters.md
- test/unit/phys/parameters/mci_parameters/input_read_all.json
- test/unit/phys/parameters/mci_parameters/mci_parameters_test.cpp
As discussed in the call, keep configurations between iterations by default.
> default store-config is true.

- CMakeLists.txt
- cmake/dca_testing.cmake
this will prevent multi gpu tests from running if multiple GPU's are not present
> Don't run multi GPU test if enough GPU's aren't present

- build-aux/daint_gpu.cmake
- build-aux/daint_gpu_load_modules.sh
- src/profiling/CMakeLists.txt
- test/integration/cluster_solver/ss_ct_hyb/CMakeLists.txt
- test/integration/cluster_solver/ss_ct_hyb/NiO_no_change_test.cpp
- test/integration/coarsegraining/CMakeLists.txt
- test/integration/coarsegraining/coarsegraining_test.cpp
- test/system-level/analysis/dca_pp_up_down_full/analysis_dca_pp_up_down_full_test.cpp
- test/system-level/analysis/dca_pp_up_down_sym/analysis_dca_pp_up_down_sym_test.cpp
- test/unit/profiling/CMakeLists.txt
The Daint build was broken after an update to cuda removed support for the spefic version we were using. I found that it is much easier to rely on system modules where possible rather than maintaining easy-build just for Daint, as it mixes system modules with very few self built tools. Lets see if this works from the jenkins environment.
> Fix daint build

- include/dca/parallel/mpi_concurrency/mpi_concurrency.hpp
- include/dca/testing/dca_mpi_test_environment.hpp
- test/integration/cluster_solver/ctaux/bilayer_lattice/Nc1_interband/bilayer_lattice_Nc1_interband.cpp
- test/integration/cluster_solver/ctaux/bilayer_lattice/Nc1_intra_plus_interband/bilayer_lattice_Nc1_intra_plus_interband.cpp
- test/integration/cluster_solver/ctaux/bilayer_lattice/Nc1_intraband/bilayer_lattice_Nc1_intraband.cpp
- test/integration/cluster_solver/ctaux/square_lattice/Nc4_nn/square_lattice_Nc4_nn.cpp
- test/integration/cluster_solver/ctaux/square_lattice/Nc4_onSite_plus_nn/square_lattice_Nc4_onSite_plus_nn.cpp
- test/integration/cluster_solver/ctint/ctint_fe_as_test.cpp
- test/integration/cluster_solver/ctint/ctint_hund_lattice_test.cpp
- test/integration/cluster_solver/ctint/ctint_square_lattice_test.cpp
- test/integration/cluster_solver/ss_ct_hyb/NiO_no_change_test.cpp
- test/integration/coarsegraining/coarsegraining_test.cpp
- test/integration/statistical_tests/FeAs/ctint_fe_as_validation_stattest.cpp
- test/integration/statistical_tests/bilayer_lattice/ctaux_bilayer_verification_stattest.cpp
- test/integration/statistical_tests/bilayer_lattice/ctint_hund_validation_stattest.cpp
- test/integration/statistical_tests/real_materials/NiO_stattest.cpp
- test/system-level/dca/dca_sp_DCA+_mpi_cuda_test.cpp
- test/system-level/dca/dca_sp_DCA+_mpi_test.cpp
Nice example of Kernighan's law here. 
MI isn't to be taken lightly virtual base classes more so. That's all still there and should be stripped away but this takes care of the issue with gtest.
> fix pure virtual function calls involving MPIConcurrency and gtest

- include/dca/phys/models/general_interaction.hpp
In current master a puzzling segv will occur in debug, and generally in release. This occurs if for install you have
"single-band-hubbard-model" instead of "single-band-Hubbard-model" in your input.
> assert with message if there are no interacting sites

- build-aux/spock_cray_build.sh
- build-aux/spock_load_cray_modules.sh
- build-aux/summit_load_modules.sh
- cmake/dca_config.cmake
- include/dca/parallel/mpi_concurrency/dca_mpi.h
- include/dca/parallel/mpi_concurrency/mpi_collective_max.hpp
- include/dca/parallel/mpi_concurrency/mpi_collective_min.hpp
- include/dca/parallel/mpi_concurrency/mpi_collective_sum.hpp
- include/dca/parallel/mpi_concurrency/mpi_concurrency.hpp
- include/dca/parallel/mpi_concurrency/mpi_gang.hpp
- include/dca/parallel/mpi_concurrency/mpi_gather.hpp
- include/dca/parallel/mpi_concurrency/mpi_packing.hpp
- include/dca/parallel/mpi_concurrency/mpi_processor_grouping.hpp
- include/dca/parallel/mpi_concurrency/mpi_type_map.hpp
- include/dca/phys/parameters/mci_parameters.hpp
This patch aliases `MPI_CXX_*` types to their corresponding `MPI_C_*` types to work around non-compliance of MPICH 3.4 with the MPI 3.1 standard (https://www.mpi-forum.org/docs/mpi-3.1/mpi31-report/node48.htm#Node48).
> Mpi workaround

- include/dca/linalg/matrix.hpp
- include/dca/linalg/reshapable_matrix.hpp
- include/dca/linalg/util/copy.hpp
- src/linalg/util/error_gpu.cpp
- test/unit/linalg/reshapable_matrix_cpu_test.cpp
hip can't deal with pitch size of source = 0 for memoryCopy2D
> [AMD Port] Fixing Matrix's use of memoryCopy2D with hip

- include/dca/phys/dca_step/cluster_solver/ctaux/ctaux_cluster_solver.hpp
- include/dca/phys/dca_step/cluster_solver/ctaux/structs/vertex_pair.hpp
- include/dca/phys/dca_step/cluster_solver/ctint/ctint_cluster_solver.hpp
- include/dca/phys/dca_step/cluster_solver/ctint/walker/ctint_walker_base.hpp
- include/dca/phys/dca_step/cluster_solver/shared_tools/accumulation/time_correlator.hpp
- include/dca/phys/dca_step/cluster_solver/ss_ct_hyb/ss_ct_hyb_cluster_solver.hpp
- include/dca/phys/dca_step/cluster_solver/ss_ct_hyb/ss_ct_hyb_walker.hpp
- include/dca/phys/dca_step/cluster_solver/ss_ct_hyb/structures/hybridization_vertex.hpp
- include/dca/phys/dca_step/cluster_solver/stdthread_qmci/qmci_autocorrelation_data.hpp
- include/dca/phys/dca_step/cluster_solver/stdthread_qmci/stdthread_qmci_cluster_solver.hpp
- include/dca/phys/dca_step/cluster_solver/stdthread_qmci/stdthread_qmci_walker.hpp
- test/integration/coarsegraining/coarsegraining_test.cpp
Get rid of raw pointer G0Interpolator in TimeCorrelation.
Also fixed a number of warnings.
> Autocorrelation cleanup

- include/dca/phys/models/analytic_hamiltonians/threeband_hubbard.hpp
The correct way to do this was more complicated than I thought.
> fix for threeband model H0_WQ

- include/dca/io/hdf5/hdf5_reader.hpp
- include/dca/io/hdf5/hdf5_writer.hpp
- include/dca/io/reader.hpp
- include/dca/io/writer.hpp
- include/dca/phys/dca_data/dca_data.hpp
- include/dca/phys/dca_loop/dca_loop.hpp
- include/dca/phys/parameters/output_parameters.hpp
- src/io/CMakeLists.txt
- src/io/adios2/adios2_reader.cpp
- src/io/hdf5/CMakeLists.txt
- src/io/hdf5/hdf5_reader.cpp
- src/util/CMakeLists.txt
- src/util/ModernStringUtils.cpp
- src/util/ModernStringUtils.hpp
- test/unit/phys/parameters/output_parameters/input_read_all.json
- test/unit/phys/parameters/output_parameters/output_parameters_test.cpp
This should make it possible to use hdf5 file output from previous versions of DCA++ with the current version.
> Fix reading of legacy hdf5 files

- include/dca/io/adios2/adios2_reader.hpp
- include/dca/io/hdf5/hdf5_reader.hpp
- include/dca/io/hdf5/hdf5_writer.hpp
- include/dca/io/json/json_reader.hpp
- include/dca/io/reader.hpp
- include/dca/phys/dca_data/dca_data.hpp
- include/dca/phys/dca_loop/dca_loop.hpp
- include/dca/phys/dca_step/cluster_mapping/update_chemical_potential.hpp
- include/dca/phys/parameters/physics_parameters.hpp
- src/io/hdf5/hdf5_reader.cpp
- src/io/hdf5/hdf5_writer.cpp
- src/phys/domains/time_and_frequency/frequency_domain.cpp
- src/phys/domains/time_and_frequency/time_domain.cpp
- src/phys/domains/time_and_frequency/time_domain_left_oriented.cpp
- test/unit/io/json_reader_test.cpp
- test/unit/phys/CMakeLists.txt
- test/unit/phys/dca_data/CMakeLists.txt
- test/unit/phys/dca_data/dca_data_test.cpp
- test/unit/phys/dca_data/input_hdf5.json
- test/unit/phys/dca_data/input_read_hdf5.json
- test/unit/phys/domains/time_and_frequency/frequency_domain_test.cpp
- test/unit/phys/domains/time_and_frequency/time_domain_left_oriented_test.cpp
- test/unit/phys/domains/time_and_frequency/time_domain_test.cpp
A regression resulting the chemical potential being read from the starting iteration instead of the final iteration when reading hdf5 files for the initial self energy is fixed in this PR.
> Fix hdf5 chemical potential read

- cmake/dca_config.cmake
- include/dca/phys/dca_step/cluster_solver/ctaux/ctaux_cluster_solver.hpp
- include/dca/phys/dca_step/cluster_solver/ctaux/ctaux_walker.hpp
- include/dca/phys/dca_step/cluster_solver/ctint/ctint_cluster_solver.hpp
- include/dca/phys/dca_step/cluster_solver/ctint/walker/ctint_walker_base.hpp
- include/dca/phys/dca_step/cluster_solver/ctint/walker/ctint_walker_cpu.hpp
- include/dca/phys/dca_step/cluster_solver/ctint/walker/ctint_walker_cpu_submatrix.hpp
- include/dca/phys/dca_step/cluster_solver/ctint/walker/ctint_walker_gpu_submatrix.hpp
- include/dca/phys/dca_step/cluster_solver/ctint/walker/ctint_walker_submatrix_base.hpp
- include/dca/phys/dca_step/cluster_solver/ctint/walker/submat_impl.cpp
- include/dca/phys/dca_step/cluster_solver/ctint/walker/submat_impl.hpp
- include/dca/phys/dca_step/cluster_solver/ctint/walker/tools/d_matrix_builder.hpp
- include/dca/phys/dca_step/cluster_solver/ctint/walker/tools/d_matrix_builder_gpu.hpp
- include/dca/phys/dca_step/cluster_solver/stdthread_qmci/stdthread_qmci_cluster_solver.hpp
- include/dca/phys/dca_step/cluster_solver/stdthread_qmci/stdthread_qmci_walker.hpp
- include/dca/phys/models/tight_binding_model.hpp
- src/io/hdf5/hdf5_writer.cpp
- test/performance/phys/ctint/ctint_walker_performance_test.cpp
- test/unit/phys/dca_step/cluster_solver/ctint/walker/ct_int_walker_multinsertion_test.cpp
- test/unit/phys/dca_step/cluster_solver/ctint/walker/ct_int_walker_submatrix_gpu_complex_test.cpp
- test/unit/phys/dca_step/cluster_solver/ctint/walker/ct_int_walker_submatrix_gpu_test.cpp
- test/unit/phys/dca_step/cluster_solver/ctint/walker/ct_int_walker_submatrix_test.cpp
- test/unit/phys/dca_step/cluster_solver/ctint/walker/ct_int_walker_test.cpp
- test/unit/phys/dca_step/cluster_solver/ctint/walker/walker_wrapper.hpp
- test/unit/phys/dca_step/cluster_solver/ctint/walker/walker_wrapper_submatrix.hpp
Make the DMatrixBuilder into a  proper objects owned by a cluster solver.  They are no longer global static horrors.  This makes better testing possible and ends confusing issues with there state across iterations and between CPU and GPU implementations.
There is still an issue with the GPU DMatrixBuilder though to CTINT is broken for GPU at the moment.
> Refactor ctint walker

- build-aux/frontier_load_modules.sh
- include/dca/util/cuda2hip.h
- test/unit/linalg/util/check_RC_test.cpp
OLCF did not update openblas modules against Core/25.03 so the implicit load of that breaks the build.
rocm6.3.1 vs gtest breaks check_RC_test due EXPECT_THROW thread spawn.
> Explicit cray core module and unit test fix

- cmake/FindMAGMA.cmake
As the title says.  Older versions of Magma should be fine since magma_v2.h has been around for quite some time and it is what we include.
> New magma version has no magma.h

- include/dca/linalg/util/memory.hpp
This event sync code is more complicated than needed and doesn't work as intended with hip.
> this way of using event sync fails in hip

- build-aux/frontier_build.sh
- include/dca/linalg/blas/use_device.hpp
- include/dca/linalg/matrixop.hpp
- include/dca/linalg/util/stream_container.hpp
- include/dca/phys/dca_step/cluster_solver/ctaux/walker/tools/g0_interpolation/g0_interpolation_gpu.hpp
- include/dca/phys/dca_step/cluster_solver/ctint/structs/device_configuration_manager.hpp
- include/dca/phys/dca_step/cluster_solver/ctint/structs/interaction_vertices.hpp
- include/dca/phys/dca_step/cluster_solver/ctint/walker/ctint_walker_base.hpp
- include/dca/phys/dca_step/cluster_solver/ctint/walker/ctint_walker_cpu_submatrix.hpp
- include/dca/phys/dca_step/cluster_solver/ctint/walker/ctint_walker_gpu_submatrix.hpp
- include/dca/phys/dca_step/cluster_solver/ctint/walker/ctint_walker_submatrix_base.hpp
- include/dca/phys/dca_step/cluster_solver/shared_tools/interpolation/g0_interpolation_gpu.hpp
- include/dca/phys/parameters/parameters.hpp
- src/phys/dca_step/cluster_solver/ctint/walker/walker_kernels.cu
- test/unit/linalg/vector_cpu_gpu_test.cpp
- test/unit/linalg/vector_cpu_test.cpp
- test/unit/linalg/vector_gpu_test.cpp
- test/unit/phys/dca_step/cluster_solver/ctint/walker/CMakeLists.txt
- test/unit/phys/dca_step/cluster_solver/ctint/walker/ct_int_walker_multinsertion_test.cpp
- test/unit/phys/dca_step/cluster_solver/ctint/walker/ct_int_walker_submatrix_gpu_complex_test.cpp
- test/unit/phys/dca_step/cluster_solver/ctint/walker/ct_int_walker_submatrix_gpu_test.cpp
- test/unit/phys/dca_step/cluster_solver/ctint/walker/ct_int_walker_submatrix_test.cpp
- test/unit/phys/dca_step/cluster_solver/ctint/walker/ct_int_walker_test.cpp
- test/unit/phys/dca_step/cluster_solver/ctint/walker/walker_wrapper.hpp
- test/unit/phys/dca_step/cluster_solver/ctint/walker/walker_wrapper_submatrix.hpp
- test/unit/phys/dca_step/cluster_solver/stub_rng.hpp
- test/unit/phys/dca_step/cluster_solver/test_setup.hpp
Removing spin parallelism which is non performant and unstable on AMD and works against future plans to make spin no longer a "special" index.
> Remove stream spin parallelism
