ATTRIBUTIONS.md
include/dca/parallel/no_threading/no_threading.hpp
include/dca/parallel/stdthread/stdthread.hpp
include/dca/parallel/stdthread/thread_pool/COPYING
include/dca/parallel/stdthread/thread_pool/thread_pool.hpp
include/dca/phys/dca_algorithms/compute_free_greens_function.hpp
include/dca/phys/dca_step/cluster_mapping/coarsegraining/coarsegraining_routines.hpp
include/dca/phys/dca_step/cluster_mapping/coarsegraining/quadrature_integration.hpp
include/dca/phys/dca_step/cluster_solver/high_temperature_series_expansion/compute_bubble.hpp
include/dca/phys/dca_step/cluster_solver/high_temperature_series_expansion/sigma_perturbation_2nd_order.inc
include/dca/phys/domains/cluster/cluster_domain.hpp
src/parallel/no_threading/no_threading.cpp
src/parallel/stdthread/CMakeLists.txt
src/parallel/stdthread/stdthread.cpp
src/parallel/stdthread/thread_pool/thread_pool.cpp
test/unit/parallel/no_threading/no_threading_test.cpp
test/unit/parallel/stdthread/CMakeLists.txt
test/unit/parallel/stdthread/stdthread_test.cpp
test/unit/parallel/stdthread/thread_pool/CMakeLists.txt
test/unit/parallel/stdthread/thread_pool/thread_pool_test.cpp

Should contain the development repo thread spawning fix.  Builds, still requires testing.

gpu_trunk: thread pool

---

CMakeLists.txt
include/dca/math/function_transform/special_transforms/kernels_interface.hpp
include/dca/math/function_transform/special_transforms/space_transform_2D.hpp
include/dca/math/function_transform/special_transforms/space_transform_2D_gpu.hpp
src/math/function_transform/CMakeLists.txt
src/math/function_transform/special_transforms_kernels.cu
test/unit/math/CMakeLists.txt
test/unit/math/function_transform/CMakeLists.txt
test/unit/math/function_transform/input.json
test/unit/math/function_transform/space_transform_2D_gpu_test.cpp

Specialization of a transformation f(r1,r2) -> \tilde{f}(k1,k2) for CPU and GPU. Needed by the two particle accumulator.

2d space transform

---

include/dca/linalg/matrix.hpp
include/dca/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/ndft/cached_ndft_base.hpp
include/dca/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/ndft/cached_ndft_cpu.hpp
include/dca/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/ndft/cached_ndft_gpu.hpp
include/dca/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/ndft/cached_ndft_template.hpp
include/dca/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/ndft/kernels_interface.hpp
include/dca/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/ndft/triple.hpp
src/phys/dca_step/cluster_solver/CMakeLists.txt
src/phys/dca_step/cluster_solver/shared_tools/CMakeLists.txt
src/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/ndft/ndft_kernels.cu
test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/CMakeLists.txt
test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/accumulation_test.hpp
test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/ndft/CMakeLists.txt
test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/ndft/cached_ndft_cpu_test.cpp
test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/ndft/cached_ndft_gpu_test.cpp

This PR merges the class responsible for transforming the data from time to frequency in the two particle accumulator. It was mostly reviewed in https://github.com/CompFUSE/DCA-develop/pull/132: just a different test fixture is used.
~It depends on #16 and #22.~

2d frequency transform

---

include/dca/phys/error_computation_type.hpp
include/dca/phys/parameters/mci_parameters.hpp
src/phys/CMakeLists.txt
src/phys/error_computation_type.cpp
test/unit/phys/parameters/mci_parameters/CMakeLists.txt
test/unit/phys/parameters/mci_parameters/input_read_all.json
test/unit/phys/parameters/mci_parameters/mci_parameters_test.cpp
tools/complete_input.json

Quick PR to add a couple of options.

Add parameters for threaded solver and accumulator.

---

CMakeLists.txt
include/dca/linalg/matrix.hpp
include/dca/linalg/util/atomic_add_cuda.cu.hpp
include/dca/phys/dca_step/cluster_solver/shared_tools/accumulation/sp/sp_accumulator.hpp
include/dca/phys/dca_step/cluster_solver/shared_tools/accumulation/sp/sp_accumulator_gpu.hpp
test/integration/nfft/dnfft_1d_test.cpp
test/performance/CMakeLists.txt
test/performance/phys/accumulation/CMakeLists.txt
test/performance/phys/accumulation/input.json
test/performance/phys/accumulation/sp_accumulation_performance_test.cpp
test/unit/function/domains/dmn_variadic_test.cpp
test/unit/linalg/matrix_gpu_test.cpp
test/unit/math/nfft/dnfft_1d_gpu_test.cpp
test/unit/phys/dca_step/cluster_solver/shared_tools/CMakeLists.txt
test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/accumulation_test.hpp
test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/mock_parameters.hpp
test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/single_sector_accumulation_test.hpp
test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/sp/CMakeLists.txt
test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/sp/sp_accumulator_gpu_test.cpp
test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/ndft/cached_ndft_cpu_test.cpp
test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/ndft/cached_ndft_gpu_test.cpp

Single particle accumulator based on the dnfft(_gpu) class.
Depends on ~#27 #22 #16~.

Sp accumulator

---

include/dca/linalg/vector.hpp

Self-explanatory mini PR from gpu_trunk.

empty vectors don't allocate.

---

test/integration/cluster_solver/ctaux/bilayer_lattice/Nc1_interband/bilayer_lattice_Nc1_interband.cpp
test/integration/cluster_solver/ctaux/bilayer_lattice/Nc1_intra_plus_interband/bilayer_lattice_Nc1_intra_plus_interband.cpp
test/integration/cluster_solver/ctaux/bilayer_lattice/Nc1_intraband/bilayer_lattice_Nc1_intraband.cpp

Addresses the instability in pycycle of these tests.

increased tolerance of bilayer tests.

---

include/dca/linalg/vector.hpp
include/dca/phys/dca_step/cluster_solver/ctaux/ctaux_walker.hpp
include/dca/phys/dca_step/cluster_solver/ctaux/walker/tools/g0_interpolation/g0_interpolation_gpu.inc
include/dca/phys/dca_step/cluster_solver/ctaux/walker/tools/n_matrix_tools/n_matrix_tools_gpu.inc
include/dca/phys/dca_step/cluster_solver/ctaux/walker/tools/n_tools.hpp
include/dca/phys/parameters/mc_solver_parameters.hpp
src/math/nfft/dnfft_1d_kernels.cu
test/performance/phys/ctaux/CMakeLists.txt
test/performance/phys/ctaux/bilayer_lattice_input.json
test/performance/phys/ctaux/ctaux_walker_performance_test.cpp

Depends on #34.
Slight performance improvement of the CT-AUX walker using async memory transfers.

Walker async improvement

---

include/dca/parallel/util/get_workload.hpp
include/dca/phys/dca_step/cluster_solver/ctaux/walker/tools/n_tools.hpp
include/dca/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/tp_accumulator.hpp
include/dca/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/tp_accumulator_gpu.hpp
test/unit/function/domains/dmn_variadic_test.cpp
test/unit/parallel/util/call_once_per_loop_test.cpp
test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/tp_accumulator_singleband_gpu_test.cpp

Replace uint's and ulong's.

---

include/dca/phys/dca_step/cluster_solver/ctaux/ctaux_accumulator.hpp
include/dca/phys/dca_step/cluster_solver/ctaux/ctaux_cluster_solver.hpp
include/dca/phys/dca_step/cluster_solver/ctaux/ctaux_walker.hpp
include/dca/phys/dca_step/cluster_solver/ss_ct_hyb/ss_ct_hyb_accumulator.hpp
include/dca/phys/dca_step/cluster_solver/ss_ct_hyb/ss_ct_hyb_cluster_solver.hpp
include/dca/phys/dca_step/cluster_solver/ss_ct_hyb/ss_ct_hyb_walker.hpp
include/dca/phys/dca_step/cluster_solver/stdthread_qmci/stdthread_qmci_accumulator.hpp
include/dca/phys/dca_step/cluster_solver/stdthread_qmci/stdthread_qmci_cluster_solver.hpp

Updated the coding style of the threaded solver interface. No effective changes.

Clean up StdthreadQmciClusterSolver.

---

src/math/nfft/dnfft_1d_kernels.cu

Fixes a missing straightforward boundary check noted by @efdazedo.

fixed sum kernel.

---

build-aux/summit.cmake
build-aux/summit_load_modules.sh
cmake/dca_testing.cmake
test/summit_run_tests.lsf

Modifications to the CMake system that enable compilation on Summit @ ORNL, along with a script that loads the required modules, and a job submission script that runs the unit tests on Summit.

Summit cmake

---

src/linalg/blas/kernels_gpu.cu

Same improvements as in multiplyDiagonalRight/Left.

ScaleRows improvement.

---

src/linalg/lapack/multiply_diagonal_gpu.cu

Following on the discussion with Ed, this uses more CUDA threads in multiply_diagonal_right/left.

Changed thread distribution in multiply_diagonal_left/right.

---

include/dca/phys/dca_step/cluster_solver/ctaux/ctaux_walker.hpp

Fix for small measurement count.

Fix possible division by 0 in CT-AUX updateShell.

---

include/dca/phys/dca_step/cluster_solver/ctint/accumulator/ctint_accumulator.hpp

This is essentially a  thin wrapper around the sp and tp accumulator. It has no unit test as it needs the not yet merged walker. Let me know if this is not acceptable.

CT-INT accumulator.

---

include/dca/phys/parameters/mc_solver_parameters.hpp
misc/wiki/Parameters.md
test/integration/cluster_solver/stdthread_qmci/stdthread_ctaux_tp_test_shared_input.json
test/unit/phys/parameters/mc_solver_parameters/mc_solver_parameters_ct_aux_test.cpp

Temporary patch to at least solve the problem in a default configuration. It is anyway the more sensible default.

workaround for #184

---

test/unit/parallel/mpi_concurrency/mpi_gather_test.cpp

With spectrum MPI and gcc 8.1.1 the usage of a std::unique_ptr in mpi_gather_test results in MPI_init after MPI_finalize
The full ctest should always pass on summit.

Fix MPI crash after last test assertion in mpi_gather_test

---

include/dca/phys/dca_step/symmetrization/symmetrize_single_particle_function.hpp

As discussed with @maierta, here is an extra symmetrization for real hamiltonians, where G(w) = conj(G(-w)), on top of G(w) = conj(transposed(G(-w)))

Better frequency symmetrization for real hamiltonians.

---

build-aux/cades.cmake
build-aux/cades_load_modules.sh

This is pretty dirty but will allow postdocs in CNMS to use CADES CONDO for dev work.

Cades build working as of Oct 1 2020

---

CMakeLists.txt
build-aux/cades_load_modules.sh
src/linalg/util/CMakeLists.txt
src/phys/dca_step/cluster_solver/ctaux/CMakeLists.txt

some modules changed and software locations as well

post lustre migration fixes

---

build-aux/cades.cmake
tutorials/tc/preconfigured/cades.job.dca_U=6_d=0.95_Nc=4.sh
tutorials/tc/preconfigured/job.analysis_U=6_d=0.95_Nc=4.sh
tutorials/tc/preconfigured/job.dca_U=6_d=0.95_Nc=4.sh

Fix bad CUDA architecture for cades.cmake.  Modify tutorial scripts to be more easily run.

fix for CADES build and tutorial scripts

---

cmake/dca_modules/rebuild.cmake
cmake/dca_testing.cmake
test/unit/linalg/blas/complex_op_test.cpp
test/unit/linalg/blas/complex_op_test_kernels.hpp

reenable strict module and commit info in build
actually fixed complex_op_test

Amd port cleanup

---

src/io/json/CMakeLists.txt

Not sure why this didn't show up on summit.

leconte reveals missing CUDA link.

---

build-aux/cades.cmake
build-aux/cades_load_modules.sh

fix hdf5 typo and update cmake version

Fix Cades Build

---

build-aux/cades_no_gpu.cmake
include/dca/linalg/util/handle_functions.hpp
include/dca/platform/gpu_definitions.h
test/unit/function/CMakeLists.txt
test/unit/function/function_construction_test.cpp
test/unit/parallel/mpi_concurrency/CMakeLists.txt
test/unit/parallel/mpi_concurrency/mpi_gather_test.cpp

Fix no gpu build

---

include/dca/math/random/std_random_wrapper.hpp
include/dca/phys/dca_step/cluster_solver/stdthread_qmci/stdthread_qmci_cluster_solver.hpp
test/integration/cluster_solver/ctint/ctint_square_lattice_tp_test.cpp
test/integration/cluster_solver/ctint/square_lattice_tp_input.json
test/integration/cluster_solver/stdthread_qmci/gpu/stdthread_ctaux_gpu_tp_test.cpp
test/integration/cluster_solver/stdthread_qmci/gpu/threaded_input.json
test/integration/cluster_solver/stdthread_qmci/stdthread_ctint_test_nonshared_input.json
test/integration/coarsegraining/input_bilayer.json

I a number of places extensive tests had non portable numbers of threads specified and other defects.

Extensive threaded tests fix

---

include/dca/io/hdf5/hdf5_reader.hpp
include/dca/io/hdf5/hdf5_writer.hpp
include/dca/io/json/json_reader.hpp
include/dca/io/json/json_writer.hpp
include/dca/io/reader.hpp
include/dca/io/writer.hpp
include/dca/phys/four_point_type.hpp
include/dca/phys/models/analytic_hamiltonians/triangular_lattice.hpp
include/dca/phys/models/general_interaction.hpp
include/dca/phys/parameters/dca_parameters.hpp
include/dca/phys/parameters/ed_solver_parameters.hpp
include/dca/phys/parameters/four_point_parameters.hpp
include/dca/phys/parameters/mci_parameters.hpp
src/io/hdf5/hdf5_writer.cpp
src/io/json/json_reader.cpp
src/io/json/json_writer.cpp
src/phys/four_point_type.cpp
test/unit/io/json_reader_test.cpp

This should apply the essential fixes from the master branch.

Back ports from master

---

include/dca/phys/dca_algorithms/compute_free_greens_function.hpp
include/dca/phys/dca_data/dca_data.hpp
include/dca/phys/dca_loop/dca_loop.hpp

wrong nesting for concurrency operation

Fix issue with reading Initial Self Energy from HDF5

---

include/dca/io/hdf5/hdf5_reader.hpp
include/dca/io/hdf5/hdf5_writer.hpp
include/dca/io/writer.hpp
include/dca/phys/models/analytic_hamiltonians/Kagome_hubbard.hpp
src/io/hdf5/hdf5_reader.cpp
test/unit/io/reader_test.cpp
test/unit/phys/dca_step/lattice_mapping/deconvolution/deconvolution_routines_test.cpp

Fix some warnings and failing tests

Kagome branch

---

cmake/dca_config.cmake
include/dca/io/hdf5/hdf5_writer.hpp
include/dca/io/writer.hpp
include/dca/phys/models/analytic_hamiltonians/Kagome_hubbard.hpp
include/dca/phys/parameters/model_parameters.hpp
src/io/hdf5/hdf5_reader.cpp
test/unit/io/reader_test.cpp
test/unit/phys/dca_step/lattice_mapping/deconvolution/deconvolution_routines_test.cpp

Implemented as a 3-orbital model on a triangular lattice

Added model file for Kagome lattice Hubbard model

---

include/dca/phys/dca_analysis/bse_solver/bse_cluster_solver_ext.hpp
include/dca/phys/dca_analysis/bse_solver/bse_lattice_solver_ext.hpp
include/dca/phys/parameters/analysis_parameters.hpp

Add option for dumping intermediate S of q omega tensors

Debug s of q omega demo

---

applications/analysis/chi_q_omega.cpp
cmake/GNUCompilers.cmake
cmake/inspectCompiler.cmake
include/dca/parallel/no_concurrency/no_concurrency.hpp
include/dca/parallel/no_threading/no_threading.hpp
include/dca/phys/dca_step/cluster_solver/ss_ct_hyb/accumulator/sp/sp_accumulator_nfft.hpp
include/dca/phys/dca_step/cluster_solver/ss_ct_hyb/ss_ct_hyb_accumulator.hpp
include/dca/phys/dca_step/cluster_solver/ss_ct_hyb/ss_ct_hyb_cluster_solver.hpp
include/dca/phys/dca_step/cluster_solver/ss_ct_hyb/ss_ct_hyb_walker.hpp
include/dca/phys/dca_step/cluster_solver/ss_ct_hyb/ss_hybridization_solver_routines.hpp
include/dca/phys/dca_step/cluster_solver/ss_ct_hyb/walker_tools/ss_hybridization_walker_routines.hpp
include/dca/phys/dca_step/lattice_mapping/interpolation/interpolation_tp.hpp
include/dca/phys/parameters/output_parameters.hpp
src/parallel/no_concurrency/CMakeLists.txt
test/integration/phys/lattice_mapping/CMakeLists.txt
test/unit/parallel/no_concurrency/CMakeLists.txt
test/unit/phys/dca_algorithms/CMakeLists.txt
test/unit/phys/domains/cluster/cluster_domain_test.cpp

further updates for smoother operation and build on summit

S of q omega demo

---

examples/bilayer/g4_input_analysis.json
examples/bilayer/input.json
examples/bilayer/training_input.json
examples/g4/conv_g4.json
examples/single_band_hubbard/conv.json
examples/single_band_hubbard/slp_training.json
examples/three_band/input_Emery_G4.json
examples/three_band/input_Emery_conv.json
examples/three_band/input_G4.json
examples/three_band/input_conv.json

basic example inputs for multiband models

Multiband example inputs

---

include/dca/phys/dca_data/dca_data.hpp

Small fix so that main analysis can read to new hdf5 output.

multistep hdf5 writing fix for main analysis

---

include/dca/linalg/reshapable_matrix.hpp
include/dca/linalg/util/allocators/managed_allocator.hpp
include/dca/linalg/util/memory.hpp
include/dca/math/nfft/dnfft_1d_gpu.hpp
include/dca/phys/dca_loop/dca_loop.hpp
include/dca/phys/dca_step/cluster_solver/ctint/walker/ctint_walker_gpu_submatrix.hpp
include/dca/platform/dca_gpu_complex.h
libs/googletest-1.8.0/include/gtest/gtest.h
src/io/io_types.cpp
test/unit/linalg/matrix_gpu_test.cpp
test/unit/linalg/reshapable_matrix_gpu_test.cpp
test/unit/phys/dca_step/cluster_solver/ctaux/walker/ct_aux_walker_test.cpp
test/unit/phys/dca_step/cluster_solver/ctint/walker/tools/d_matrix_builder_gpu_test.cpp
test/unit/phys/dca_step/cluster_solver/ctint/walker/walker_wrapper_submatrix.hpp
test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/ndft/cached_ndft_gpu_test.cpp
test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/tp_accumulator_complex_g0_gpu_test.cpp
test/unit/phys/domains/cluster/cluster_domain_test.cpp

Trying to bring the code to the point where we so no warnings.

Fix many compilation Warnings

---

include/dca/phys/models/analytic_hamiltonians/util.hpp
test/test_automation/ci/run_step.sh

This fixes #301 and is actually @maierta or @PZMai 's work.

fix HInteractions to include minus_r terms

---

build-aux/frontier_rocm6_load_modules.sh
include/dca/phys/dca_step/cluster_solver/ctaux/ctaux_cluster_solver.hpp
include/dca/phys/dca_step/cluster_solver/ctaux/ctaux_walker.hpp
test/unit/phys/dca_step/cluster_solver/ctaux/walker/ct_aux_walker_test.cpp
test/unit/phys/dca_step/cluster_solver/ctaux/walker/walker_wrapper.hpp

Two emergency fixes to unbreak the build.

Fix ctaux build Fix libfabric build on frontier

---

build-aux/frontier_rocm6_load_modules.sh
include/dca/phys/dca_step/cluster_solver/ctaux/ctaux_walker.hpp

Small updates for Frontier hang debugging.

update compiler to OLCF best practice, remove debug output

---

build-aux/frontier_rocm6_load_modules.sh
include/dca/linalg/matrix.hpp
include/dca/parallel/mpi_concurrency/mpi_collective_sum.hpp
include/dca/phys/dca_step/cluster_solver/ctaux/ctaux_walker.hpp
include/dca/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/g4_helper.cuh
include/dca/phys/dca_step/cluster_solver/shared_tools/cluster_helper.cuh
include/dca/util/cuda2hip.h
src/math/nfft/nfft_helper.cu
src/phys/dca_step/cluster_solver/ctint/device_helper/ctint_helper.cu
src/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/g4_helper.cu
src/phys/dca_step/cluster_solver/shared_tools/cluster_helper.cu
src/phys/dca_step/cluster_solver/shared_tools/solver_helper.cu

Fixes for copies to symbols on CUDA, mpi collective change from AllReduce to Reduce->Broadcast.

La3 ni2 o7 mpi collective change
